require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Metrics/MethodLength:
  Max: 20

AllCops:
  NewCops: enable
